# -*- coding: utf-8 -*-
"""Fourier_part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13h8WPOrRIwg4FlTS0NGaItp76MW6xFfl
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sympy as sp
import scipy.integrate as spi
import random
import math as mt


def user_simpson(func2,a,b,n,n1):
    h = float((b-a)/n)
    result = (1/3)*(func2(a,n1)+func2(b,n1))
    for i in range(1,n,2):
        result+= 4*(func2(a+i*h,n1))
    for j in range(2,n-1,2):
        result+=2*(func2(a+j*h,n1))
    result*=h/3
    return result

def user_trapezoidal (f,a,b,n,n1):
    h=(b-a)/n
    x=[a]
    y=[]
    total=0
    for i in range (1,n):
        step=x[0]+i*h
        x.append(step)
    x.append(b)
    q=len(x)
    u=q-1
    for j in range(1,q-1):
        z=f(x[j],n1)
        y.append(z)
    for ele in range(0, len(y)): 
        total = total +y[ele]
    total=2*(total) + f(x[0],n1) + f(x[u],n1)
    res=(h/2)*total
    return res


l1=0  # for parabola 0
l2=np.pi  # for parabola pi
hp=(abs(l2)-abs(l1))/2
#####################################################################
k=20    # NO. OF TERMS OF AN AND BN 
period=2  #no. of periods
###################         FUNCTIONS     ########################################
# def func(x):                                  
#     return x
#########
def func(x):              #PARABOLA FUNCTION
    return x*(x-(np.pi))
#########

def a_n(x,n):
    f_of_x=func(x)
    return f_of_x * np.cos((x*n*mt.pi)/hp) 

def b_n(x,n):
    f_of_x=func(x)
    return f_of_x * np.sin((x*n*mt.pi)/hp)



####################
x=np.linspace(l1,period*l2,100)

####################
z=spi.simps(func(np.linspace(l1,l2)),np.linspace(l1,l2),dx=0.01)


a0=z/hp
a_0= a0/2
b0=0
print("a0 =" + str(a0))
            #####################################################

an_inbuilt=[]
an_user_simpson=[]
an_user_trapezoidal=[]
y=[]
series_of_sum_simpson=[]
series_of_sum_trapezoidal=[]

f_of_x=[]
bn_inbuilt=[]
bn_user_simpson=[]
bn_user_trapezoidal=[]

for i in range (1,k):
    integrand=a_n(x,i) 
    y1=func(x)*np.cos((i*x*mt.pi)/hp)  # AN USING INBUILT
    y2=spi.simps(y1,x,dx=0.01)
    an_inbuilt.append(y2)
 #############################
    y5=func(x)*np.sin((i*x*mt.pi)/hp)  # BN USING INBUILT
    y6=spi.simps(y5,x,dx=0.01) 
    bn_inbuilt.append(y6)
  #############################
    y3=user_simpson(a_n,l1,l2,50,i)  # AN USING USER SIMPSONN
    an_user_simpson.append(y3)
  ################################
    y4=user_trapezoidal(a_n,l1,l2,500,i)   # AN USING USER TRAPEZOIDAL
    an_user_trapezoidal.append(y4)
  ################################
    y9=user_simpson(b_n,l1,l2,10,i)      # BN USING USER SIMPSON
    bn_user_simpson.append(y9)
################################
    y13=user_trapezoidal(b_n,l1,l2,10,i)  # BN USING USER TRAPEZOIDAL
    bn_user_trapezoidal.append(y13)
################################
n=np.arange(1,k,1)
# print(n,bn_inbuilt)
plt.plot(n,an_inbuilt,"r*-",label="an_inbuilt")
plt.plot(n,bn_inbuilt,"b*-",label="bn_inbuit")
plt.plot(n,an_user_simpson,label="an_user_simpson")
plt.plot(n,bn_user_simpson,label="bn_user_simpson")
plt.plot(n,an_user_trapezoidal,label="an_user_trapezoidal")
plt.plot(n,bn_user_trapezoidal,label="bn_user_trapezoidal")
plt.xlabel("n")
plt.ylabel("an and bn")
plt.title("an and bn V/S n")
plt.legend()
plt.grid(True)
plt.show()

##################################
x=np.linspace(l1,period*l2,100)
for j in range(0, len(x)):
    x1=x[j]
    series_sum=a_0
    series_sum_simpson=a_0
    series_sum_trapezoidal=a_0
    for q in range (1,k):
        series_sum+=an_inbuilt[q-1]*mt.cos((q*x1*mt.pi)/hp) + bn_inbuilt[q-1]*mt.sin((q*x1*mt.pi)/hp)
        series_sum_simpson+=an_user_simpson[q-1]*mt.cos((q*x1*mt.pi)/hp) +bn_user_simpson[q-1]*mt.sin((q*x1*mt.pi)/hp)
        series_sum_trapezoidal += an_user_trapezoidal[q-1]*mt.cos((q*x1*mt.pi)/hp) + bn_user_trapezoidal[q-1]*mt.sin((q*x1*mt.pi)/hp)
    y.append(series_sum)
    series_of_sum_simpson.append(series_sum_simpson)
    series_of_sum_trapezoidal.append(series_sum_trapezoidal)
# #####################################################################

list_of_tuples = list(zip(an_inbuilt,an_user_simpson,an_user_trapezoidal,bn_inbuilt))
list_of_tuples
df = pd.DataFrame(list_of_tuples,columns=["a_n_inbilt","an_user_simpson","an_user_trapezoidal","bn_inbuilt"])
print(df)
list_of_tuples = list(zip(x,y,series_of_sum_simpson,series_of_sum_trapezoidal))
list_of_tuples
df = pd.DataFrame(list_of_tuples,columns=["X","s_n_inbilt","sn_user_simpson","sn_user_trapezoidal"])
print(df)

# ################################################
plt.plot(x,y,'g--',label=" inbuilt simpson integration")
plt.plot(x,series_of_sum_trapezoidal,'b:',label="user trapezoidal integration")
plt.plot(x,series_of_sum_simpson,'r*',label="user simpson integration")
plt.title("FUNCTION PLOT")
plt.xlabel("X")
plt.ylabel("sum of series - F(x)")
plt.grid(True)
plt.legend()
plt.show()

x=np.arange(1,k,1)

######################################
an_2=np.array(an_inbuilt)
bn_2=np.array(bn_inbuilt)
an_2_simps=np.array(an_user_simpson)
bn_2_simps=np.array(bn_user_simpson)
an_2_trap=np.array(an_user_trapezoidal)
bn_2_trap=np.array(bn_user_trapezoidal)
anbnsum=np.array(np.square(an_2)+np.square(bn_2))
anbnsimpssum=np.array(np.square(an_2_simps)+np.square(bn_2_simps))
anbntrapsum=np.array(np.square(an_2_trap)+np.square(bn_2_trap))
plt.plot(x,anbnsum,'r*-',label='inbuilt')
plt.plot(x,anbnsimpssum,'g:',label='user simpson')
plt.plot(x,anbntrapsum,'b',label='user trap')
plt.xlabel('n')
plt.ylabel('an^2+bn^2')
plt.title('an^2+bn^2 V/S n')
plt.legend()
plt.grid(True)
plt.show()
# print(an_inbuilt)
#####################################
an_inbuilt=[x/an_inbuilt[0] for x in an_inbuilt]
bn_inbuilt=[x/bn_inbuilt[0] for x in bn_inbuilt]
an_user_simpson=[x/an_inbuilt[0] for x in an_user_simpson]
bn_user_simpson=[x/bn_inbuilt[0] for x in bn_user_simpson]
an_user_trapezoidal=[x/an_inbuilt[0] for x in an_user_trapezoidal]
bn_user_trapezoidal=[x/bn_inbuilt[0] for x in bn_user_trapezoidal]

plt.plot(x,an_inbuilt,"r.-",label="an_inbuilt")
plt.plot(x,bn_inbuilt,"b.-",label="bn_inbuilt")
plt.plot(x,an_user_simpson,label="an_user_simpson")
plt.plot(x,bn_user_simpson,label="bn_user_simpson")
plt.plot(x,an_user_trapezoidal,label="an_user_trapezoidal")
plt.plot(x,bn_user_trapezoidal,label="bn_user_trapezoidal")
plt.xlabel("n")
plt.ylabel("an/a1 and bn/b1")
plt.title("an/a1 and bn/b1 V/S n")
plt.legend()
plt.grid()
plt.show()



